default:
  navigation:
    - title: Mujeres
      subtitle: Categorías
      url: /t/mujeres
      items:
        - :title: Faldas
          :url: /t/mujeres/skirts
        - :title: Vestidos
          :url: /t/mujeres/dresses
        - :title: Shirts and Blouses
          :url: /t/mujeres/shirts-and-blouses
        - :title: Sueters
          :url: /t/mujeres/sweaters
        - :title: Poleras y Tops
          :url: /t/mujeres/tops-and-t-shirts
        - :title: Chaquetas y Abrigos
          :url: /t/mujeres/jackets-and-coats
    - title: Men
      subtitle: Categories
      url: /t/men
      items:
        - :title: Shirts
          :url: /t/men/shirts
        - :title: T-shirts
          :url: /t/men/t-shirts
        - :title: Sweaters
          :url: /t/men/sweaters
        - :title: Jackets and Coats
          :url: /t/men/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Sportswear
      subtitle: Categories
      url: /t/sportswear
      items:
        - :title: Tops
          :url: /t/sportswear/tops
        - :title: Sweatshirts
          :url: /t/sportswear/sweatshirts
        - :title: Pants
          :url: /t/sportswear/pants
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
