default:
  navigation:
    - title: Nuevos Lanzamientos
      subtitle: Colecciones
      url: /t/colecciones
      items:
        -  title: Tendencias
           :url:  /t/colecciones/tendencias
    - title: Mujeres
      subtitle: Vestimenta
      url: /t/mujeres
      items:
        - :title: Faldas
          :url: /t/mujeres/skirts
        - :title: Vestidos
          :url: /t/mujeres/dresses
        - :title: Sueters
          :url: /t/mujeres/sweaters
        - :title: Poleras y Tops
          :url: /t/mujeres/tops-and-t-shirts
        - :title: Chaquetas y Abrigos
          :url: /t/mujeres/jackets-and-coats
        - :title: Zapatillas
          :url: /t/mujeres/calzado
    - title: Hombres
      subtitle: Vestimenta
      url: /t/hombres
      items:
        - :title: Poleras
          :url: /t/hombres/poleras-m
        - :title: Sueters
          :url: /t/hombres/sweaters
        - :title: Chaquetas y Abrigos
          :url: /t/hombres/jackets-and-coats
        - :title: Pantalones Deportivos
          :url: /t/hombres/pants-m     
        - :title: zapatillas
          :url: /t/hombres/calzado 
    - title: Niños
      subtitle: Vestimenta
      url: /t/infantil
      items:
        - :title: Tops
          :url: /t/infantil/tops
        - :title: Vestidos
          :url: /t/infantil/dresses-g
        - :title: Pantalones
          :url: /t/infantil/pants-c  
        - :title: zapatillas
          :url: /t/infantil/calzado    
    - title: Liquidación
      subtitle: Destacados
      url: /t/liquidacion
